'use client';
import {useState} from 'react';
import {MapPin,SlidersHorizontal,Car,ChevronRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetTrigger} from '@/components/ui/sheet';
import {Choice,Field} from './controls';
import {Lang,tr,localized} from '@/lib/i18n';
import {RecordData} from '@/lib/types';
export const money=(n:number,l:Lang)=>new Intl.NumberFormat(l==='pt'?'pt-BR':l==='es'?'es-US':'en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function VehicleCard({v,l}:{v:RecordData;l:Lang}){const t=(k:string)=>tr(l,k);return <a href={`#/${l}/vehicles/${v.id}`} className="vehicle-card"><div className="car-photo"><img src={v.image} alt={v.make+' '+v.model} loading="lazy"/>{v.featured&&<span className="badge">{t('Featured')}</span>}<span className="view-photo"><ChevronRight size={18}/></span></div><div className="car-info"><div className="car-year">{v.year} · {t(v.body)}</div><h3>{v.make} {v.model}</h3><div className="specs">{Number(v.mileage).toLocaleString()} {t('miles')}<span>·</span>{t(v.transmission)}</div><div className="car-bottom"><strong>{money(v.price,l)}</strong><span><MapPin size={13}/>{v.city}, {v.state}</span></div></div></a>}
const coords:Record<string,number[]>={'33101':[25.77,-80.19],'32801':[28.54,-81.38],'33602':[27.95,-82.46],'90001':[33.97,-118.25],'10001':[40.75,-73.99],'75201':[32.79,-96.8]};
function miles(a:string,b:string){if(a===b)return 0;if(!coords[a]||!coords[b])return Infinity;const [x,y]=coords[a],[z,w]=coords[b];const rad=Math.PI/180;return 3959*2*Math.asin(Math.sqrt(Math.sin((z-x)*rad/2)**2+Math.cos(x*rad)*Math.cos(z*rad)*Math.sin((w-y)*rad/2)**2));}
export function CatalogView({data,l,service=false,initial={}}:any){const t=(k:string)=>tr(l,k);const [f,setF]=useState<any>(initial);const [sort,setSort]=useState('Newest');const set=(k:string,v:string)=>setF({...f,[k]:v});const rows:RecordData[]=service?data.services:data.vehicles;const result=rows.filter(v=>(!f.make||v.make===f.make)&&(!f.model||v.model.toLowerCase().includes(f.model.toLowerCase()))&&(!f.year||v.year===+f.year)&&(!f.min||v.price>=+f.min)&&(!f.max||v.price<=+f.max)&&(!f.mileage||v.mileage<=+f.mileage)&&(!f.body||v.body===f.body)&&(!f.fuel||v.fuel===f.fuel)&&(!f.transmission||v.transmission===f.transmission)&&(!f.category||v.category===f.category)&&(!f.zip||miles(f.zip,v.zip)<=+(f.distance||50))).sort((a,b)=>sort==='lowest'?a.price-b.price:sort==='highest'?b.price-a.price:sort==='lowMiles'?a.mileage-b.mileage:String(b.createdAt).localeCompare(String(a.createdAt)));
const choice=(key:string,label:string,values:string[])=> <Choice label={t(label)} value={f[key]||''} onChange={v=>set(key,v)} options={[{value:'',label:t('all')},...values.map(x=>({value:x,label:t(x)}))]}/>;
const filters=<div className="filter-stack"><h3>{t('filters')}</h3>{service?choice('category','Category',Array.from(new Set(rows.map(v=>v.category)))):<>{choice('make','Make',Array.from(new Set(rows.map(v=>v.make))))}<Field label={t('Model')} value={f.model||''} onChange={(e:any)=>set('model',e.target.value)}/>{choice('year','Year',Array.from(new Set(rows.map(v=>String(v.year)))))}<div className="two"><Field type="number" min="0" label={t('Min')} value={f.min||''} onChange={(e:any)=>set('min',e.target.value)}/><Field type="number" min="0" label={t('Max')} value={f.max||''} onChange={(e:any)=>set('max',e.target.value)}/></div><Field type="number" min="0" label={t('Mileage')} value={f.mileage||''} onChange={(e:any)=>set('mileage',e.target.value)}/>{choice('body','Body',Array.from(new Set(rows.map(v=>v.body))))}{choice('fuel','Fuel',Array.from(new Set(rows.map(v=>v.fuel))))}{choice('transmission','Transmission',['Automatic','Manual'])}</>}<Field label={t('zip')} value={f.zip||''} maxLength={5} onChange={(e:any)=>set('zip',e.target.value.replace(/\D/g,''))}/>{choice('distance','Distance',['25','50','100','500','3000'])}<p className="fine">{t('zipHint')}</p><button className="text-button" onClick={()=>setF({})}>{t('reset')}</button></div>;
return <main className="page wrap"><p className="eyebrow">CAR ON LINE / {t(service?'Services':'Vehicles')}</p><h1>{t(service?'near':'featured')}</h1><p className="muted">{t('demo')}</p><div className="catalog-layout"><aside className="desktop-filters">{filters}</aside><div><div className="results-bar"><span>{result.length} {t(service?'Services':'Vehicles').toLowerCase()}</span><Sheet><SheetTrigger className="outline mobile-filter"><SlidersHorizontal size={16}/>{t('filters')}</SheetTrigger><SheetContent className="drawer"><SheetTitle>{t('filters')}</SheetTitle>{filters}</SheetContent></Sheet>{!service&&<Choice label={t('sort')} value={sort} onChange={setSort} options={['Newest','lowest','highest','lowMiles'].map(x=>({value:x,label:t(x)}))}/>}</div><div className="catalog-grid">{result.map(v=>service?<ServiceCard key={v.id} v={v} l={l}/>:<VehicleCard key={v.id} v={v} l={l}/>)}</div>{!result.length&&<div className="empty"><Car/><p>{t('empty')}</p></div>}</div></div></main>}
export function ServiceCard({v,l}:any){return <a className="service-result" href={`#/${l}/services/${v.id}`}><img src={v.image} alt={localized(v,'name',l)} loading="lazy"/><div><span className="eyebrow">{tr(l,v.category)}</span><h3>{localized(v,'name',l)}</h3><p>{localized(v,'description',l)}</p><div className="car-bottom"><span><MapPin size={14}/>{v.city}, {v.state}</span><strong>{tr(l,'quote')}</strong></div></div></a>}
