import {currentRoute} from '@/lib/navigation';
'use client';
import {useRef,useState,useEffect} from 'react';
import {Car,Wrench,ShieldCheck,Banknote,Truck,FileCheck,Settings,ChevronLeft,ChevronRight,Mouse,MapPin,Check,Pause,Play} from 'lucide-react';
import {Lang,tr,localized} from '@/lib/i18n';
import {hero,repair,detail} from '@/lib/seed';
import {Choice,Field} from './controls';
import {VehicleCard,ServiceCard} from './catalog';
const icons:any={buy:Car,sell:Car,maintenance:Wrench,repair:Settings,parts:Settings,insurance:ShieldCheck,financing:Banknote,registration:FileCheck,transport:Truck};
export function Home({l,data}:any){const t=(k:string)=>tr(l,k);const [type,setType]=useState('buy');const [make,setMake]=useState('');const [zip,setZip]=useState('');const [model,setModel]=useState('');const [year,setYear]=useState('');const [max,setMax]=useState('');const [distance,setDistance]=useState('50');const rail=useRef<HTMLDivElement>(null);const video=useRef<HTMLVideoElement>(null);const [playing,setPlaying]=useState(true);const setting=data.settings[0]||{};useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){video.current?.pause();setPlaying(false)}},[]);
function search(e:any){e.preventDefault();const q=new URLSearchParams({make,zip,model,year,max,distance,...(type!=='buy'?{category:type}:{})});location.hash=`#/${l}/${type==='sell'?'request?type=sell':type==='buy'?'vehicles?'+q:'services?'+q}`;}
return <><section className="hero"><img className="hero-image" src={hero} alt="Black sports car on a night drive" fetchPriority="high"/>{setting.video&&<video ref={video} className="hero-image" poster={hero} autoPlay muted loop playsInline preload="metadata"><source src={setting.video}/></video>}<div className="hero-shade"/><div className="hero-copy wrap"><p className="eyebrow"><span className="red-line"/>{t('eyebrow')}</p><h1>{localized(setting,'title',l)||t('hero')}</h1><p className="hero-sub">{localized(setting,'subtitle',l)||t('subtitle')}</p><div className="actions"><a className="button" href="#search" onClick={e=>{e.preventDefault();document.getElementById('search')?.scrollIntoView({behavior:'smooth'})}}>{t('find')}</a><a className="ghost" href={`#/${l}/services`}>{t('explore')}</a></div></div><div className="hero-bottom wrap"><span><Mouse size={16}/>{t('premium')}</span><div className="hero-dots"><i/><i/><i/></div>{setting.video&&<button aria-label={t(playing?'pause':'play')} onClick={()=>{if(video.current){playing?video.current.pause():video.current.play();setPlaying(!playing)}}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button>}</div><span className="hero-index">01 — 03</span></section>
<section className="search-section wrap" id="search"><div className="search-box"><h2>{t('need')}</h2><div className="search-tabs">{['buy','sell','maintenance','insurance','transport','other'].map(x=><button className={type===x?'selected':''} onClick={()=>setType(x)} key={x}>{t(x)}</button>)}</div><form onSubmit={search} className="main-search">{type==='buy'?<><Choice label={t('Make')} value={make} onChange={setMake} options={[{value:'',label:t('all')},...Array.from(new Set(data.vehicles.map((v:any)=>v.make))).map((x:any)=>({value:x,label:x}))]}/><Field label={t('Model')} value={model} onChange={(e:any)=>setModel(e.target.value)} placeholder={t('all')}/><Field type="number" min="1900" max="2030" label={t('Year')} value={year} onChange={(e:any)=>setYear(e.target.value)} placeholder={t('all')}/><Field type="number" min="0" label={t('Max')} value={max} onChange={(e:any)=>setMax(e.target.value)} placeholder="$"/></>:<Choice label={t('service')} value={type} onChange={setType} options={['sell','maintenance','repair','parts','insurance','financing','registration','transport','other'].map(x=>({value:x,label:t(x)}))}/>}<Field label={t('zip')} value={zip} pattern="[0-9]{5}" maxLength={5} placeholder="33101" onChange={(e:any)=>setZip(e.target.value)}/><Choice label={t('Distance')+' (mi)'} value={distance} onChange={setDistance} options={['25','50','100','500','3000'].map(x=>({value:x,label:x}))}/><button className="button" type="submit">{t('Search')}</button></form></div></section>
<section className="section wrap" id="services"><div className="section-head"><div><p className="eyebrow">{t('complete')}</p><h2>{t('everything')}</h2><p className="muted">{t('serviceSub')}</p></div><div className="rail-controls"><button aria-label={t('back')} onClick={()=>rail.current?.scrollBy({left:-350,behavior:'smooth'})}><ChevronLeft/></button><button aria-label={t('explore')} onClick={()=>rail.current?.scrollBy({left:350,behavior:'smooth'})}><ChevronRight/></button></div></div><div className="service-rail" ref={rail}>{Object.keys(icons).map((x,i)=>{const Icon=icons[x];return <a className="service-tile" key={x} href={`#/${l}/${x==='buy'?'vehicles':x==='sell'?'request?type=sell':'services?category='+x}`} style={{backgroundImage:`url(${i===0?data.vehicles[0]?.image:i===1?detail:repair})`}}><div className="tile-cover"/><div className="tile-content"><Icon size={27}/><div><span className="tile-number">0{i+1}</span><h3>{t(x)}</h3><p>{t('explore')}</p></div></div></a>})}</div></section>
<section className="section featured-section"><div className="wrap"><div className="section-head"><div><p className="eyebrow">{t('curated')}</p><h2>{t('featured')}</h2></div><a className="outline" href={`#/${l}/vehicles`}>{t('viewAll')}</a></div><div className="three-grid">{data.vehicles.filter((v:any)=>v.featured).slice(0,3).map((v:any)=><VehicleCard key={v.id} v={v} l={l}/>)}</div><p className="fine">{t('demo')}</p></div></section>
<section className="section wrap" id="how"><div className="center"><p className="eyebrow">{t('How')}</p><h2>{t('howTitle')}</h2></div><div className="steps">{[1,2,3].map(n=><div key={n}><span className="step-num">0{n}</span><h3>{t('step'+n)}</h3><p>{t('step'+n+'d')}</p></div>)}</div></section>
<section className="cinematic" style={{backgroundImage:`url(${detail})`}}><div className="wrap"><p className="eyebrow">CAR ON LINE</p><h2>{t('more')}</h2><a className="button" href={`#/${l}/request`}>{t('Start')}</a></div></section>
<section className="section wrap"><div className="section-head"><div><p className="eyebrow">{t('Partners')}</p><h2>{t('near')}</h2></div><a className="outline" href={`#/${l}/services`}>{t('explore')}</a></div><div className="three-grid">{data.services.filter((s:any)=>s.featured).slice(0,3).map((s:any)=><ServiceCard v={s} l={l} key={s.id}/>)}</div></section>
<section className="nation section"><div className="wrap nation-grid"><div><p className="eyebrow">{t('coast')}</p><h2>{t('nation')}</h2><p className="muted">{t('nationD')}</p><div className="nation-tags">{['transport','buy','Partners','maintenance'].map(x=><span key={x}><Check size={15}/>{t(x)}</span>)}</div></div><div className="states"><span>{t('west')}</span><strong>CA <i>—</i> TX <i>—</i> FL</strong><span>{t('network')}</span><div className="state-line"/><p>Los Angeles · Dallas · Miami · New York</p></div></div></section>
<section className="section wrap"><div className="section-head"><div><p className="eyebrow">{t('Testimonials')}</p><h2>{t('testimonials')}</h2></div><small>{t('demoTest')}</small></div><div className="testimonials">{data.testimonials.map((v:any)=><article key={v.id}><div className="stars">★★★★★</div><p>“{localized(v,'comment',l)}”</p><div className="person"><span>{v.name[0]}</span><div><strong>{v.name}</strong><small>{v.city}</small></div></div></article>)}</div></section>
{data.banners.map((b:any)=><section key={b.id} className="banner wrap" style={{backgroundImage:b.image?`url(${b.image})`:undefined}}><h2>{localized(b,'title',l)}</h2><p>{localized(b,'subtitle',l)}</p><a className="button" href={`#/${l}/request`}>{t('Start')}</a></section>)}
<section className="final-cta wrap"><p className="eyebrow">{t('moving')}</p><h2>{t('ready')}</h2><p>{t('readyD')}</p><div className="actions"><a className="button" href={`#/${l}/request`}>{t('Start')}</a><a className="outline" href={`#/${l}/contact`}>{t('talk')}</a></div></section></>}
