import {demoFetch as fetch,mediaURL,resetDemo} from '@/lib/demo-store';
'use client';
import {useState} from 'react';
import {CheckCircle,ShieldCheck} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {tr,categories} from '@/lib/i18n';
import {Choice,Field} from './controls';
export default function RequestForm({l,initialType='other',vehicle='',service=''}:any){const t=(k:string)=>tr(l,k);const [type,setType]=useState(initialType);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [consent,setConsent]=useState(false);
async function submit(e:any){e.preventDefault();if(!consent)return;setBusy(true);setError('');try{const form=new FormData(e.currentTarget);const images:string[]=[];for(const f of form.getAll('images') as File[]){if(f.size){const data=new FormData();data.set('file',f);const r=await fetch('/api/upload',{method:'POST',body:data});if(!r.ok)throw Error();images.push(((await r.json()) as any).url);}}const data={...Object.fromEntries(form.entries()),type,vehicle,service,images,consent:true};const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!res.ok)throw Error();setSuccess(((await res.json()) as any).id);}catch{setError(t('sendError'));}finally{setBusy(false)}}
if(success)return <main className="page wrap"><div className="success-box"><CheckCircle size={52}/><h1>{t('success')}</h1><p>{t('ref')}: {success.slice(0,8).toUpperCase()}</p><a className="button" href={`#/${l}`}>{t('Home')}</a></div></main>;
return <main className="page wrap request-layout"><div><p className="eyebrow">CAR ON LINE CONCIERGE</p><h1>{t('request')}</h1><p className="muted">{t('requestD')}</p><div className="request-note"><ShieldCheck/><p>{t('step2d')}</p></div>{vehicle&&<p>{t('vehicle')}: <strong>{vehicle}</strong></p>}{service&&<p>{t('service')}: <strong>{service}</strong></p>}</div><form className="request-form" onSubmit={submit}><Choice label={t('need')} value={type} onChange={setType} options={categories.map(x=>({value:x,label:t(x)}))}/><div className="three-fields"><Field label={t('Make')} name="make"/><Field label={t('Model')} name="model"/><Field type="number" min="1900" max="2030" label={t('Year')} name="year"/></div><label className="field"><span>{t('detailsRequest')} *</span><textarea name="description" required rows={4} maxLength={3000}/></label><Field label={t('zip')+' *'} name="zip" required pattern="[0-9]{5}" inputMode="numeric" maxLength={5} placeholder="33101"/><div className="two"><Field label={t('Name')+' *'} name="name" required maxLength={100}/><Field label={t('Email')+' *'} name="email" type="email" required maxLength={200}/></div><Field label={t('Phone')+' *'} name="phone" type="tel" required maxLength={30}/><Field label={t('images')+' · '+t('optional')+' (JPG, PNG, WebP, 5 MB)'} name="images" type="file" multiple accept="image/jpeg,image/png,image/webp"/><label className="check-line"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>{t('consent')} <a href={`#/${l}/privacy`} target="_blank">{t('privacy')}</a></span></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy||!consent} className="button full" type="submit">{busy?t('sending'):t('submit')}</button></form></main>}
