import {seed} from './seed';
import {entities} from './types';
const DATABASE='car-on-line-pages-demo-v1';
const urls=new Map<string,string>();
const urlIds=new Map<string,string>();
let connection:Promise<IDBDatabase>|null=null;
function openDatabase(){if(!connection)connection=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DATABASE,1);r.onupgradeneeded=()=>{for(const name of ['catalog','leads','media'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'id'})};r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();connection=null};resolve(r.result)};r.onerror=()=>{connection=null;reject(r.error)};r.onblocked=()=>reject(new Error('Close other tabs and try again.'));});return connection;}
async function request<T>(store:string,mode:IDBTransactionMode,run:(s:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const database=await openDatabase();return new Promise((resolve,reject)=>{const tx=database.transaction(store,mode);const r=run(tx.objectStore(store));let value:T;r.onsuccess=()=>{value=r.result};tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error||r.error);tx.onabort=()=>reject(tx.error||new Error('Storage unavailable'));});}
const all=<T=any>(store:string)=>request<T[]>(store,'readonly',s=>s.getAll());
function objectURL(id:string,blob:Blob){let url=urls.get(id);if(!url){url=URL.createObjectURL(blob);urls.set(id,url);urlIds.set(url,id)}return url;}
export function mediaURL(id:string){return urls.get(id)||'';}
function stored(value:any):any{if(typeof value==='string'&&urlIds.has(value))return 'demo-media:'+urlIds.get(value);if(Array.isArray(value))return value.map(stored);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,stored(v)]));return value;}
function hydrated(value:any):any{if(typeof value==='string'&&value.startsWith('demo-media:'))return urls.get(value.slice(11))||'';if(Array.isArray(value))return value.map(hydrated);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,hydrated(v)]));return value;}
async function catalog(admin=false){const records=await all('catalog');const media=await all('media');for(const m of media)objectURL(m.id,m.blob);const data:any=structuredClone(seed);for(const kind of entities){const changes=records.filter((x:any)=>x.kind===kind);const merged=new Map(data[kind].map((x:any)=>[x.id,x]));for(const r of changes)merged.set(r.record.id,r.record);data[kind]=Array.from(merged.values()).filter((r:any)=>!r.deleted&&(admin||r.active!==false));}if(admin){data.leads=(await all('leads')).sort((a:any,b:any)=>b.date.localeCompare(a.date));data.media=media.map(({blob,...m}:any)=>({...m,url:urls.get(m.id)}));}return hydrated(data);}
function response(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});}
function validLead(d:any){return d&&typeof d.name==='string'&&d.name.trim()&&typeof d.email==='string'&&/^\S+@\S+\.\S+$/.test(d.email)&&/^\d{5}$/.test(d.zip)&&typeof d.phone==='string'&&d.phone.trim()&&typeof d.description==='string'&&d.description.trim()&&d.type&&d.consent===true;}
export async function demoFetch(path:string,options:RequestInit={}):Promise<Response>{try{const method=options.method||'GET';if(path==='/api/data'&&method==='GET')return response(await catalog());if(path==='/api/admin'&&method==='GET')return response(await catalog(true));if(path==='/api/upload'&&method==='POST'){const f=(options.body as FormData).get('file');if(!(f instanceof File)||!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(f.type)||f.size>25*1024*1024)return response({error:'Use JPG, PNG, WebP, MP4 or WebM, up to 25 MB.'},400);const id=crypto.randomUUID();await request('media','readwrite',s=>s.put({id,name:f.name,type:f.type,size:f.size,blob:f,public:1,date:new Date().toISOString()}));return response({id,url:objectURL(id,f)});}
if(path==='/api/leads'&&method==='POST'){const d=JSON.parse(options.body as string);if(!validLead(d)||JSON.stringify(d).length>20000)return response({error:'Invalid request'},400);const id=crypto.randomUUID();await request('leads','readwrite',s=>s.put({...stored(d),id,status:'New',date:new Date().toISOString()}));return response({id});}
if(path==='/api/admin'&&method==='POST'){const d=JSON.parse(options.body as string);if(d.kind==='leads'){if(!['New','Contacted','In Progress','Completed','Cancelled'].includes(d.status))return response({error:'Invalid status'},400);const row=await request<any>('leads','readonly',s=>s.get(d.id));if(!row)return response({error:'Not found'},404);await request('leads','readwrite',s=>s.put({...row,status:d.status}));return response({ok:true});}if(!(entities as readonly string[]).includes(d.kind)||!d.record||typeof d.record.id!=='string')return response({error:'Invalid record'},400);await request('catalog','readwrite',s=>s.put({id:d.kind+':'+d.record.id,kind:d.kind,record:stored(d.record)}));return response({ok:true});}return response({error:'Not found'},404);}catch(error){console.error('Demo storage error',error);return response({error:'Browser storage is unavailable or full. Your input has not been cleared.'},503);}}
export async function resetDemo(){const database=await openDatabase();await new Promise<void>((resolve,reject)=>{const tx=database.transaction(['catalog','leads','media'],'readwrite');for(const name of ['catalog','leads','media'])tx.objectStore(name).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();urlIds.clear();}
