import {asset} from './navigation';
import {Catalog} from './types';
export const photo=(id:string,w=900)=>asset(`media/${id}.webp`);
export const hero=photo('photo-1715733965684-81ad72895d60',1920);
export const repair=photo('photo-1625047509248-ec889cbff17f');
export const detail=photo('photo-1607860115477-7b3700e055b6');
const cars=[['Porsche','911 Carrera',2023,112900,8200,'Coupe','Gasoline','photo-1715733965665-4a75f34b23c3','Miami','FL','33101'],['BMW','M4 Competition',2022,72900,18400,'Coupe','Gasoline','photo-1658557941831-e1198a078c89','Orlando','FL','32801'],['Mercedes-Benz','C 300',2021,32900,26100,'Sedan','Gasoline','photo-1686562483617-3cf08d81e117','Miami','FL','33101'],['Audi','Q5 Premium',2022,38900,22700,'SUV','Gasoline','photo-1621349337628-d4f1c1a24114','Tampa','FL','33602'],['Tesla','Model 3 Long Range',2023,34900,14200,'Sedan','Electric','photo-1655792291377-7fa0cc1bed5a','Los Angeles','CA','90001'],['Ford','Mustang GT',2022,42900,16800,'Coupe','Gasoline','photo-1655628266959-12ec3f839a46','Dallas','TX','75201'],['Land Rover','Range Rover Sport',2023,79900,11200,'SUV','Gasoline','photo-1707771244468-fe987ad9b76f','New York','NY','10001'],['Toyota','RAV4 Hybrid',2024,36900,9400,'SUV','Hybrid','photo-1739796216379-e5b6793f313a','Orlando','FL','32801']];
const serviceNames=[['maintenance','Routine maintenance','Manutenção preventiva','Mantenimiento preventivo'],['repair','Expert auto repair','Reparo especializado','Reparación especializada'],['detailing','Premium detailing','Estética premium','Estética premium'],['insurance','Auto insurance options','Opções de seguro','Opciones de seguro'],['financing','Vehicle financing','Financiamento de veículos','Financiamiento de vehículos'],['transport','Interstate transport','Transporte interestadual','Transporte interestatal'],['registration','Registration & title','Registro e documentação','Registro y título'],['parts','Parts & tires','Peças e pneus','Repuestos y neumáticos']];
export const seed:Catalog={
vehicles:cars.map((c,i)=>({id:String(c[2])+'-'+String(c[0]+'-'+c[1]).toLowerCase().replaceAll(' ','-'),make:c[0],model:c[1],name:c[0]+' '+c[1],year:c[2],price:c[3],mileage:c[4],body:c[5],fuel:c[6],image:photo(c[7] as string),images:[photo(c[7] as string,1400)],city:c[8],state:c[9],zip:c[10],transmission:'Automatic',vin:'DEMO'+String(i+1).padStart(13,'0'),engine:i===4?'Dual motor':'Demo specification',exterior:'See photos',interior:'Black',dealer:'partner-'+(i%6),active:true,featured:i<3,description:'An illustrative vehicle listing. Photos are representative; price, specifications and availability are demonstration data.',description_pt:'Anúncio ilustrativo. Fotos representativas; preço, especificações e disponibilidade são dados de demonstração.',description_es:'Anuncio ilustrativo. Fotos representativas; precio, especificaciones y disponibilidad son datos de demostración.',features:'Bluetooth, Navigation, Parking sensors',createdAt:'2026-09-'+String(28-i)})),
services:serviceNames.map((s,i)=>({id:s[0],category:s[0],name:s[1],name_pt:s[2],name_es:s[3],description:'Tell us what you need. Our team will help you explore the available options.',description_pt:'Conte o que você precisa. Nossa equipe ajuda você a encontrar as opções disponíveis.',description_es:'Cuéntanos qué necesitas. Nuestro equipo te ayudará a explorar las opciones disponibles.',partner:'partner-'+(i%6),image:i===2?detail:repair,city:i%2?'Orlando':'Miami',state:'FL',zip:i%2?'32801':'33101',active:true,featured:i<3})),
partners:['Coastal Motor Group','Precision Auto Works','Shine Automotive','Drive Forward Solutions','Cross Country Auto','Metro Vehicle Services'].map((name,i)=>({id:'partner-'+i,name,category:serviceNames[i][0],city:i%2?'Orlando':'Miami',state:'FL',zip:i%2?'32801':'33101',description:'Demonstration partner',description_pt:'Parceiro de demonstração',description_es:'Socio de demostración',rating:4.8,active:true})),
categories:serviceNames.map(s=>({id:s[0],name:s[1],name_pt:s[2],name_es:s[3],active:true})),
testimonials:[['Alex R.','Miami, FL','One place to start, instead of a dozen different searches.','Um só lugar para começar, em vez de dezenas de buscas.','Un lugar para empezar, en vez de decenas de búsquedas.'],['Jordan M.','Orlando, FL','A much simpler way to explore my next car.','Um jeito muito mais simples de procurar meu próximo carro.','Una forma más sencilla de buscar mi próximo auto.'],['Taylor S.','Tampa, FL','From maintenance to transport, it all comes together.','Da manutenção ao transporte, tudo no mesmo lugar.','Desde mantenimiento hasta transporte, todo conectado.'],['Casey L.','Dallas, TX','Having someone guide the process makes a difference.','Ter alguém acompanhando o processo faz diferença.','Tener a alguien que acompañe el proceso marca la diferencia.']].map((s,i)=>({id:'testimonial-'+i,name:s[0],city:s[1],comment:s[2],comment_pt:s[3],comment_es:s[4],rating:5,active:true})),
banners:[],settings:[{id:'site-main',name:'Homepage',video:asset('media/hero.mp4'),active:true}]
};
